# Site settings
title: Coding in the Rain
description: >
  Coding in the Rain by Andrew Carter
baseurl: ""
url: http://ascarter.dev
github_username: ascarter

# Serve extra directories
include: [".well-known"]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#highlighter: rouge
permalink: date
exclude:
  - config.ru
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.markdown
  - bin
  - public
  - vendor
  - new_site
  - serve.sh
